SELECT LCT.UF, CLB.NOME_COLABORADOR, YEAR(SAL.DATA_PAGAMENTO) AS ANO, SUM(SAL.SALARIO) AS TOTAL_SALARIO
FROM COLABORADORES CLB
LEFT JOIN SALARIOS SAL ON SAL.ID_COLABORADOR = CLB.ID_COLABORADOR
LEFT JOIN LOCAL_DE_TRABALHO LCT ON LCT.ID_COLABORADOR = CLB.ID_COLABORADOR
GROUP BY LT.UF, C.NOME_COLABORADOR, YEAR(SAL.DATA_PAGAMENTO) 
WHERE YEAR(SAL.DATA_PAGAMENTO) = 2014